version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enterprise_db
    ports:
      - '5432:5432'
    volumes:
      - product_management_platform_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - product_management_platform_redis_data:/data

volumes:
  product_management_platform_data:
  product_management_platform_redis_data:
